export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL"

export const NEW_REVIEW_REQUEST="NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS="NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET="NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL="NEW_REVIEW_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"